# Generated by Django 4.2.5 on 2023-09-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=95)),
                ('time', models.DateTimeField()),
                ('docs', models.TextField()),
                ('status', models.CharField(choices=[('bajarilmoqda', 'Bajarilmoqda'), ('bajarildi', 'Bajarildi'), ('tugatildi', 'Tugatildi')], max_length=17)),
            ],
        ),
    ]
